services:
  qdrant:
      image: qdrant/qdrant:latest
      container_name: qdrant_instance
      ports:
        - "6333:6333"
        - "6334:6334"
      environment:
      - QDRANT__TELEMETRY_DISABLED=true
      healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6333/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      volumes:
        - qdrant_data:/qdrant/storage 
      networks:
        - main_network
        
volumes:
  qdrant_data:
    external: true
  
networks:
  main_network:
    external: true