services:
  zitadel:
    restart: 'always'
    image: 'ghcr.io/zitadel/zitadel:latest'
    command: 'start-from-init --masterkey "${ZITADEL_MASTERKEY}" --tlsMode disabled'
    container_name: zitadel
    ports:
      - 4006:8080
    networks:
      - main_network
    env_file:
      - .env
      
networks:
  main_network:
    external: true