services:
  timescale_db:
    image: timescale/timescaledb:latest-pg16
    container_name: timescaledb
    environment:
      - POSTGRES_PASSWORD=<placeholder>
    volumes:
      - timescalesb_data: /var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  timescalesb_data:
    external: true


networks:
  main_network:
    external: true