services:
  pgdb:
    container_name: postgres_db
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=<placeholder>
      - POSTGRES_USER=dragon
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
      - pgdata_lib:/usr/lib/postgresql
      - pgdata_share:/usr/share/postgresql
    networks:
      - main_network

  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - 4001:8080
    networks:
      - main_network

volumes:
  pgdata_share:
    external: true
  pgdata_lib:
    external: true
  pgdata:
    external: true
networks:
  main_network:
    external: true