services:
  pgdb:
    container_name: postgres_db
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=utkarshC2@
      - POSTGRES_USER=dragon
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - main_network

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - main_network

volumes:
  pgdata:
    external: true
networks:
  main_network:
    external: true